#!/bin/bash

export BANO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export LOG_DIR=$BANO_DIR/log
export DATA_DIR=${DATA_DIR:-/data/project/bano_data}
export DOWNLOAD_DIR=${DOWNLOAD_DIR:-/data/download}
export IMPOSM_CACHE_DIR=${IMPOSM_CACHE_DIR:-/data/bano_imposm_cache}
export BANO_CACHE_DIR=$DATA_DIR/bano_cache
export BAN_CACHE_DIR=$DATA_DIR/ban_cache
export CADASTRE_CACHE_DIR=$DATA_DIR/cadastre_cache
export BAL_CACHE_DIR=$DATA_DIR/bal_cache
export EXPIRE_TILES_DIR=$DATA_DIR/expire_tiles
export CSV_DIR=$DATA_DIR/csv_insee
export EXPORT_SAS_DIR=${EXPORT_SAS_DIR:-/data/sas_web}
export EXPORT_WEB_DIR=${EXPORT_WEB_DIR:-/data/work/bano.openstreetmap.fr/www/web/data/}
export TMP_DIR=${TMP_DIR:-/data/tmp}
export SCHEMA_CIBLE=public
export LANG=${LANG:-fr_FR.UTF-8}


POSTGRES_USER=${POSTGRES_USER:-cadastre}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
POSTGRES_HOST=${POSTGRES_HOST:-localhost}
POSTGRES_PORT=${POSTGRES_PORT:-5432}

POSTGRES_DB_OSM=${POSTGRES_DB:-osm}
POSTGRES_DB_CADASTRE=${POSTGRES_DB:-cadastre}

export PGCON_OSM="$POSTGRES_USER${POSTGRES_PASSWORD:+:$POSTGRES_PASSWORD}@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB_OSM"
export pgsql_OSM="psql postgresql://${PGCON_OSM} -v ON_ERROR_STOP=1"
export PG_OSM="host='$POSTGRES_HOST' port=$POSTGRES_PORT dbname='$POSTGRES_DB_OSM' user='$POSTGRES_USER' ${POSTGRES_PASSWORD:+password='$POSTGRES_PASSWORD'}"

export PGCON_CADASTRE="$POSTGRES_USER${POSTGRES_PASSWORD:+:$POSTGRES_PASSWORD}@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB_CADASTRE"
export pgsql_CADASTRE="psql postgresql://${PGCON_CADASTRE} -v ON_ERROR_STOP=1"
export PG_CADASTRE="host='$POSTGRES_HOST' port=$POSTGRES_PORT dbname='$POSTGRES_DB_CADASTRE' user='$POSTGRES_USER' ${POSTGRES_PASSWORD:+password='$POSTGRES_PASSWORD'}"
