#!/bin/bash

WORK_DIR=${WORK_DIR:-"/data/work/cadastre.openstreetmap.fr"}
DATA_DIR=${DATA_DIR:-"$WORK_DIR/data"}
HIDDEN_DIR=${HIDDEN_DIR:-"$WORK_DIR/hidden"}
LOG_DIR=${LOG_DIR:-"$WORK_DIR/logs"}
BIN_DIR=${BIN_DIR:-"/data/project/cadastre.openstreetmap.fr/bin"}
