#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title BANO - Rapprochements
graph_vlabel Nb de voies
graph_category bano
match.label Voies rapprochees
nomatch.label Voies non rapprochees
EOM
        exit 0;;
esac

psql cadastre -c "select concat('match.value ',count(*)::text) from (select count(*), fantoir from cumul_adresses where source='CADASTRE' and voie_osm!='' group by fantoir) as f" -At
psql cadastre -c "select concat('nomatch.value ',count(*)::text) from (select count(*), fantoir from cumul_adresses where source='CADASTRE' and (voie_osm='' or voie_osm is null) group by fantoir) as f" -At


