#!/bin/sh

# script pour graphes munin de la BANO sur le décompte global des adresses

case $1 in
   config)
        cat <<'EOM'
graph_title BANO - Contenu
graph_vlabel BANO
graph_category bano
cumul.label Cumul
cadastre.label Source cadastre
match.label Source cadastre rapprochee avec OSM
nomatch.label Source cadastre non rapprochee avec OSM
osm.label Source OSM
opendata.label Source opendata
EOM
        exit 0;;
esac

psql cadastre -c "select concat('cumul.value ',count(*)::text) from cumul_adresses;" -At
psql cadastre -c "select concat('cadastre.value ',count(*)::text) from cumul_adresses where source='CADASTRE';" -At
psql cadastre -c "select concat('match.value ',count(*)::text) from cumul_adresses where source='CADASTRE' and voie_osm != '';" -At
psql cadastre -c "select concat('nomatch.value ',count(*)::text) from cumul_adresses where source='CADASTRE' and (voie_osm = '' or voie_osm is null);" -At
psql cadastre -c "select concat('osm.value ',count(*)::text) from cumul_adresses where source='OSM';" -At
psql cadastre -c "select concat('opendata.value ',count(*)::text) from cumul_adresses where source like 'OD%';" -At
